es:
  build: es
  volumes:
   - $PWD/es/config:/usr/share/elasticsearch/config
   - $PWD/es/data:/data
  ports:
   - "9200:9200"
   - "9300:9300"

web:
  build: web
  volumes:
   - $PWD/web/src/public:/src/public
  ports:
   - "8089:8089"
  links:
   - es:es


